{
 "title": "Alerts",
 "description": "Show current firing and pending alerts, and  severity alert counts.",
 "tags": [
  "prometheus",
  "alerts"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "version", "query": "1" }
  ]
 },
 "panels": [
  { "title": "Severity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alerts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(ALERTS{alertname!=\"DeadMansSwitch\",alertstate=\"firing\"} > 0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Critical",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(ALERTS{alertname!=\"DeadMansSwitch\",alertstate=\"firing\",severity=\"critical\"} > 0) OR on() vector(0)",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ]
    }
   ]
  },
  {
   "title": "Warning",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(ALERTS{alertname!=\"DeadMansSwitch\",alertstate=\"firing\",severity=\"warning\"} > 0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Info",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(ALERTS{alertname!=\"DeadMansSwitch\",alertstate=\"firing\",severity=\"info\"} > 0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "None",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(ALERTS{alertname!=\"DeadMansSwitch\",alertstate=\"firing\",severity=\"none\"} > 0) OR on() vector(0)"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Firing",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "ALERTS{alertname!=\"DeadMansSwitch\",alertstate='firing'} > 0"
    }
   ]
  }
 ]
}