{
 "title": "HA CVIM-MON Cluster Resource Usage",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Stack",
    "query": "label_values(container_start_time_seconds, pod)"
   },
   { "name": "version", "query": "1" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CVIM-MON Stacks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(min by (pod_name)(container_start_time_seconds{pod=~\"prometheus.*alertmanager-0\"}))"
    }
   ]
  },
  {
   "title": "All Containers CPU Usage [5m]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[5m]))"
    }
   ]
  },
  {
   "title": "CVIM-MON Stacks RX [5m]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 1 },
   "format": "bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "8 * sum(rate(container_network_receive_bytes_total{namespace=~\"$Stack\"}[5m]))"
    }
   ]
  },
  {
   "title": "Portworx RX [30s]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 1 },
   "format": "bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "8 * sum((px_network_io_received_bytes{})/scalar(avg(prometheus_target_interval_length_seconds)))"
    }
   ]
  },
  {
   "title": "Portworx Storage Read [30s]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 1 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(px_volume_vol_read_bytes{})/30"
    }
   ]
  },
  {
   "title": "Cluster Cores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(machine_cpu_cores)" }
   ]
  },
  {
   "title": "CVIM-MON Stacks CPU Usage [5m]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 3 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$Stack\"}[5m]))"
    }
   ]
  },
  {
   "title": "CVIM-MON Stacks TX [5m]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 3 },
   "format": "bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "8 * sum(rate(container_network_transmit_bytes_total{namespace=~\"$Stack\"}[5m]))"
    }
   ]
  },
  {
   "title": "Portworx TX [30s]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 3 },
   "format": "bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "8 * sum((px_network_io_bytessent{})/scalar(avg(prometheus_target_interval_length_seconds)))"
    }
   ]
  },
  {
   "title": "Portworx Storage Write [30s]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 3 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(px_volume_vol_written_bytes{})/30"
    }
   ]
  },
  {
   "title": "Stack Resource Usage Summary",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=~\"$Stack\"}[5m]))"
    },
    {
     "expr": "sum by (namespace) (container_memory_working_set_bytes{namespace=~\"$Stack\"})"
    },
    {
     "expr": "8 * sum by (namespace) (rate(container_network_transmit_bytes_total{namespace=~\"$Stack\"}[5m]))"
    },
    {
     "expr": "8 * sum by (namespace) (rate(container_network_receive_bytes_total{namespace=~\"$Stack\"}[5m]))"
    },
    {
     "expr": "sum by (namespace) (px_volume_usage_bytes{namespace=~\"$Stack\"})"
    },
    {
     "expr": "sum by (namespace) (px_volume_capacity_bytes{namespace=~\"$Stack\"})"
    },
    {
     "expr": "sum by (namespace) (px_volume_usage_bytes{namespace=~\"$Stack\"})/sum by (namespace) (px_volume_capacity_bytes{namespace=~\"$Stack\"})"
    },
    {
     "expr": "sum by (namespace) (px_volume_vol_read_bytes{namespace=~\"$Stack\"})/30"
    },
    {
     "expr": "sum by (namespace) (px_volume_vol_written_bytes{namespace=~\"$Stack\"})/30"
    },
    {
     "expr": "ceil(sum by (namespace) (px_volume_vol_writes{namespace=~\"$Stack\"}+px_volume_vol_reads{namespace=~\"$Stack\"})/30)"
    },
    {
     "expr": "time() - max by (namespace)(container_start_time_seconds{pod=~\"prometheus.*alertmanager-0\"})"
    }
   ]
  },
  {
   "title": "Containers CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 Containers CPU Usage in Cluster [5m]",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "topk( 10, rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\"}[5m]))",
       "legendFormat": "{{ pod_name }}: {{kubernetes_io_hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CVIM-MON Stacks Network Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 RX/TX Prometheus Containers in Cluster [5m] ",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bps", "label": "TX (-) / RX (+)" }
     ],
     "targets": [
      {
       "expr": "topk(5, 8 * rate (container_network_receive_bytes_total{interface=\"eth0\",pod=~\"prom.*\"}[5m]))",
       "legendFormat": "RX {{ pod }} {{kubernetes_io_hostname}}"
      },
      {
       "expr": "topk(5, 8 * rate (container_network_transmit_bytes_total{interface=\"eth0\",pod=~\"prom.*\"}[5m]))",
       "legendFormat": "TX {{ pod }} {{kubernetes_io_hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CVIM-MON Stacks Storage Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stacks Storage Usage [30s]",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "Bps", "label": "Write (-) / Read (+)" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace)(px_volume_vol_read_bytes{})/30",
       "legendFormat": "Read {{namespace}}"
      },
      {
       "expr": "sum by (namespace)(px_volume_vol_written_bytes{})/30",
       "legendFormat": "Write {{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Portworx Network Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Portworx Total RX/TX Network Usage in Cluster [30s]",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bps", "label": "TX (-) / RX (+)" }
     ],
     "targets": [
      {
       "expr": "8 * sum(px_network_io_received_bytes{})/30",
       "legendFormat": "RX"
      },
      {
       "expr": "8 * sum(px_network_io_bytessent{})/30",
       "legendFormat": "TX"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 Container Memory Usage in Cluster",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\"}) by (pod_name,kubernetes_io_hostname))",
       "legendFormat": "{{ pod_name }} | {{ kubernetes_io_hostname }}"
      }
     ]
    }
   ]
  }
 ]
}