{
 "title": "Cluster Health Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Kubernetes Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Masters",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_labels{label_cvimmon_io_role=\"master\"})"
    }
   ]
  },
  {
   "title": "Masters Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{cvimmon_io_role=\"master\", job=\"kubernetes-nodes\"})"
    }
   ]
  },
  {
   "title": "Masters Up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{cvimmon_io_role=\"master\", job=\"kubernetes-nodes\"} )/ sum(kube_node_labels{label_cvimmon_io_role=\"master\"})  * 100"
    }
   ]
  },
  {
   "title": "Master Memory Usage",
   "type": "gauge",
   "description": "Shows memory usage of masters in the cluster",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",cvimmon_io_role=\"master\"}) / sum (machine_memory_bytes{cvimmon_io_role=\"master\"}) * 100"
    }
   ]
  },
  {
   "title": "Master CPU Utilisation",
   "type": "gauge",
   "description": "Shows CPU Utilisation on the masters",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",cvimmon_io_role=\"master\"}[5m])) / sum (machine_cpu_cores{cvimmon_io_role=\"master\"}) * 100"
    }
   ]
  },
  {
   "title": "Masters Disk Space Utilisation",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",cvimmon_io_role=\"master\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",cvimmon_io_role=\"master\"}) * 100"
    }
   ]
  },
  {
   "title": "Network Transmit",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device=~\"br_.+\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total Workers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_labels{label_cvimmon_io_role=\"worker\"})"
    }
   ]
  },
  {
   "title": "Workers Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{cvimmon_io_role=\"worker\", job=\"kubernetes-nodes\"})"
    }
   ]
  },
  {
   "title": "Workers Up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{cvimmon_io_role=\"worker\", job=\"kubernetes-nodes\"}) / sum(kube_node_labels{label_cvimmon_io_role=\"worker\"}) * 100"
    }
   ]
  },
  {
   "title": "Worker Memory Usage",
   "type": "singlestat",
   "description": "Shows memory usage of nodes in the cluster",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",cvimmon_io_role=\"worker\"}) / sum (machine_memory_bytes{cvimmon_io_role=\"worker\"}) * 100"
    }
   ]
  },
  {
   "title": "Worker CPU Utilisation",
   "type": "singlestat",
   "description": "Shows CPU Utilisation on the nodes",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",cvimmon_io_role=\"worker\"}[5m])) / sum (machine_cpu_cores{cvimmon_io_role=\"worker\"}) * 100"
    }
   ]
  },
  {
   "title": "Workers Disk Space Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",cvimmon_io_role=\"worker\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",cvimmon_io_role=\"worker\"}) * 100"
    }
   ]
  },
  {
   "title": "Network Receive",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device=~\"br_.+\"}[5m]))"
    }
   ]
  },
  { "title": "Kubernetes Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Total Deployments",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(min(kube_deployment_status_replicas_available) without (instance, pod))"
    }
   ]
  },
  {
   "title": "Deployment Issues",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(max(kube_deployment_spec_replicas) without (instance, pod) != 0) - count(min(kube_deployment_status_replicas_available) without (instance, pod) != 0)"
    }
   ]
  },
  {
   "title": "Total Pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=\"Running\"} == 1)"
    }
   ]
  },
  {
   "title": "Pod Issues",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_waiting_reason == 1)"
    }
   ]
  },
  {
   "title": "Total Daemonsets",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(kube_daemonset_created)" }
   ]
  },
  {
   "title": "Daemonset Issues",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_daemonset_status_number_unavailable != 0)"
    }
   ]
  },
  { "title": "Kubernetes API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "API Error Rate",
   "type": "singlestat",
   "description": "Rate of API Error (5xx) requests per second",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{code=~\"^(?:5..)$\"}[5m]))"
    }
   ]
  },
  {
   "title": "API Latency",
   "type": "singlestat",
   "description": "Average Latency of the Kubernetes API",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rate(apiserver_request_latencies_bucket[5m]) > 0)"
    }
   ]
  },
  {
   "title": "API Request Rate",
   "type": "singlestat",
   "description": "Rate of API requests per second",
   "gridPos": { "h": 3, "w": 18, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{}[5m]))"
    }
   ]
  }
 ]
}