{
 "title": "Kubernetes Control Plane",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Control Plane",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-apiservers\"})"
    }
   ]
  },
  {
   "title": "Nodes Not Ready",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Memory Pressure",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Crash Looping Pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(increase(kube_pod_container_status_restarts_total[5m]) > 1)"
    }
   ]
  },
  { "title": "Control Plane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "API Servers UP",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(up{job=\"kubernetes-apiservers\"} == 1) / count(up{job=\"kubernetes-apiservers\"})) * 100"
    }
   ]
  },
  {
   "title": "API Servers Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-apiservers\"})"
    }
   ]
  },
  { "title": "Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Pod Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (sum(kube_node_status_capacity_pods) - sum(kube_pod_info)) / sum(kube_node_status_capacity_pods) * 100"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (kube_pod_status_ready{condition=\"true\"} == 1)"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 17 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"/dev/mapper/.*\",id=\"/\"}) / sum (container_fs_limit_bytes{device=~\"/dev/mapper/.*\",id=\"/\"}) * 100"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 17 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filefd_allocated) / sum(node_filefd_maximum) * 100"
    }
   ]
  },
  {
   "title": "Pods Stopped",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum ( count (kube_pod_status_ready == 1) - count (kube_pod_status_ready{condition=\"true\"} == 1))"
    }
   ]
  },
  {
   "title": "Pods Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (kube_deployment_status_replicas_unavailable == 1)"
    }
   ]
  },
  { "title": "APIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Kubernetes API",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(code) (rate(apiserver_request_count{code!=\"0\"}[5m]))",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "API Errors [1h]",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{code=~\"5..\"}[1h]))"
    }
   ]
  },
  {
   "title": "Kubernetes API Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max by (resource, verb) (rate(apiserver_request_latencies_summary_sum{verb!~\"WATCH|CONNECT\"}[5m]))  / \nmax by (resource, verb) (rate(apiserver_request_latencies_summary_count{verb!~\"WATCH|CONNECT\"}[5m]))\n> 10",
     "legendFormat": "{{ resource }} {{ verb }}"
    }
   ]
  },
  {
   "title": "Max API Latency [1h]",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 32 },
   "format": "ns",
   "valueName": "current",
   "targets": [
    {
     "expr": "max (rate(apiserver_request_latencies_summary_sum{verb!=\"WATCH\"}[1h]))  / \nmax (rate(apiserver_request_latencies_summary_count{verb!=\"WATCH\"}[1h]))"
    }
   ]
  },
  {
   "title": "Docker API",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (kubelet_docker_operations_errors[1m]))  by (operation_type) *100",
     "legendFormat": "{{ operation_type }}"
    }
   ]
  }
 ]
}