{
 "title": "Kubernetes Tiller",
 "tags": [ "Tiller" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "tillerhost",
    "query": "label_values(kube_pod_info{pod=~\"tiller-deploy-.*\"},node)"
   }
  ]
 },
 "panels": [
  { "title": "Pods State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Scheduled Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_spec_replicas{deployment=\"tiller-deploy\"}) "
    }
   ]
  },
  {
   "title": "Deployment Created",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_deployment_created{deployment=\"tiller-deploy\"} * 1000"
    }
   ]
  },
  {
   "title": "Containers failed",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_info{pod=~\"tiller-deploy-.*\"}) - sum(kube_pod_container_status_running{pod=~\"tiller-deploy-.*\"} == 1)"
    }
   ]
  },
  {
   "title": "Basic Pod Info",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": " (kube_pod_labels)* on(pod) group_left(version) (kube_pod_start_time{pod=~\"tiller-deploy-.*\"}) * 1000"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"tiller-deploy\"}"
    }
   ]
  },
  {
   "title": "Total Pod Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_info{pod=~\"tiller-deploy-.*\"})"
    }
   ]
  },
  { "title": "Resource Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 8 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=\"$tillerhost\"})"
    }
   ]
  },
  {
   "title": "Pod memory usage (on host)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum ((container_memory_working_set_bytes{pod_name=~\"tiller-deploy-.*\", name!~\"POD\"})) / sum (machine_memory_bytes{kubernetes_io_hostname=\"$tillerhost\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 8 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod_name=~\"tiller-deploy-.*\", kubernetes_io_hostname=~\"$tillerhost\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=\"$tillerhost\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"tiller-deploy-.*\", kubernetes_io_hostname=\"$tillerhost\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"tiller-deploy-.*\"}[5m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"tiller-deploy-.*\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Network Receive",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 26 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"tiller-deploy-.*\", kubernetes_io_hostname=~\"$tillerhost\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network Transmit",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 26 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"tiller-deploy-.*\", kubernetes_io_hostname=\"$tillerhost\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pods network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"tiller-deploy-.*\"}[5m])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"tiller-deploy-.*\"}[5m])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  }
 ]
}