{
 "title": "Kubernetes Pod Status",
 "description": "Basic pod (status, container name, ip, ready, scheduled) and container (running, restart, ready, terminated, waiting) information. It doesn't capture container or pod termination/restarts when kubectl pod delete pod is executed. It does capture container restarts when docker kill container is executed. All the stats are accumulated over time, so if something happened in the past, when the time series is set to now, the stats will stil show the past events.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"^$namespace$\"}, pod)"
   },
   {
    "name": "pod_ip",
    "label": "Pod IP",
    "query": "label_values(kube_pod_info{namespace=~\"^$namespace$\", pod=~\"^$pod$\"}, pod_ip)"
   },
   {
    "name": "phase",
    "label": "Phase",
    "query": "label_values(kube_pod_status_phase{namespace=~\"^$namespace$\", pod=~\"^$pod$\"}, phase)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{namespace=~\"^$namespace$\", pod=~\"^$pod$\"}, container)"
   }
  ]
 },
 "panels": [
  { "title": "Pod Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "content": "<h1><center>$phase</center></h1>"
  },
  {
   "title": "Container",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 6, "y": 1 },
   "content": "<h1><center>$container</center></h1>"
  },
  {
   "title": "IP",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 1 },
   "content": "<h1><center>$pod_ip</center></h1>"
  },
  {
   "title": "Ready",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})"
    }
   ]
  },
  {
   "title": "Scheduled",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_status_scheduled{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})"
    }
   ]
  },
  { "title": "Container Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})"
    }
   ]
  },
  {
   "title": "Ready",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})"
    }
   ]
  },
  {
   "title": "Terminated",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})"
    }
   ]
  },
  {
   "title": "Waiting",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})"
    }
   ]
  },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})",
     "legendFormat": "Restarts"
    },
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})",
     "legendFormat": "Terminated"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})",
     "legendFormat": "Waiting"
    }
   ]
  }
 ]
}