#!/usr/bin/env bash

huge_page_size=`awk '/Hugepagesize:/ {print $2}' /proc/meminfo`
huge_pages=`awk '/HugePages_Total:/ {print $2}' /proc/meminfo`

if [ "$huge_page_size" -eq "2048" ]
then
    # For 2M
    additional=1024
elif [ "$huge_page_size" -eq "1048576" ]
then
    # For 1G
    additional=1
else
    echo "Invalid page size (${huge_page_size})"
    exit 1
fi

# Kernel has its default value of max_map_count to 65536:
# REF: https://www.kernel.org/doc/Documentation/sysctl/vm.txt
#
# The maximum number of memory map areas a process may have should be the
# system default, plus any additionals VPP may require.
vpp_max_mem_areas=$((huge_pages * 2 + additional))
host_max_map_count=$((vpp_max_mem_areas + 65536))
shared_memory_max=$((huge_pages * huge_page_size * 1024))

# Create config file for persisting values
cat > /etc/sysctl.d/50-huge-pages.conf <<EOF
vm.max_map_count=$host_max_map_count
# Note: the following does NOT propagate to the containers running on
# the host, and instead, the (insanely large) default value is used.
kernel.shmmax=$shared_memory_max
EOF

# Apply setting to currently running system
/sbin/sysctl -p /etc/sysctl.d/50-huge-pages.conf
